blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/rayhandestian/UPer.li/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerabilities
    url: https://github.com/rayhandestian/UPer.li/security/policy
    about: Please report security vulnerabilities here.
